name: Compiler le script en .exe

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du contenu du repo
        uses: actions/checkout@v3 # checkout the repository content
        with:
          token: ${{ secrets.PAT }}

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - name: Sauvegarde du fichier exe
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fichier exe compilé
